let team = [
    {
        city: 'Atlanta',
        nickname: 'Hawks',
        conference: 'East',
        card: 'teamcards/atlanta.png',
        teamColor: '#cc2d31',
        wins: 38,
        losses: 44,
    },
    {
        city: 'Boston',
        nickname: 'Celtics',
        conference: 'East',
        card: 'teamcards/boston.png',
        teamColor: '#2c8548',
        wins: 51,
        losses: 31,
    },
    {
        city: 'Charlotte',
        nickname: 'Hornets',
        conference: 'East',
        card: 'teamcards/charlotte.png',
        teamColor: '#0c9d98',
        wins: 31,
        losses: 51,
    },
    {
        city: 'Chicago',
        nickname: 'Bulls',
        conference: 'East',
        card: 'teamcards/chicago.png',
        teamColor: '#be3851',
        wins: 67,
        losses: 15,
    },
    {
        city: 'Cleveland',
        nickname: 'Cavaliers',
        conference: 'East',
        card: 'teamcards/cleveland.png',
        teamColor: '#e25d3a',
        wins: 57,
        losses: 25,
    },
    {
        city: 'Dallas',
        nickname: 'Mavericks',
        conference: 'West',
        card: 'teamcards/dallas.png',
        teamColor: '#12903e',
        wins: 22,
        losses: 60,
    },
    {
        city: 'Denver',
        nickname: 'Nuggets',
        conference: 'West',
        card: 'teamcards/denver.png',
        teamColor: '#593887',
        wins: 24,
        losses: 58,
    },
    {
        city: 'Detroit',
        nickname: 'Pistons',
        conference: 'East',
        card: 'teamcards/detroit.png',
        teamColor: '#1f65b0',
        wins: 48,
        losses: 34,
    },
    {
        city: 'Golden State',
        nickname: 'Warriors',
        conference: 'West',
        card: 'teamcards/golden-state.png',
        teamColor: '#26334d',
        wins: 55,
        losses: 27,
    },
    {
        city: 'Houston',
        nickname: 'Rockets',
        conference: 'West',
        card: 'teamcards/houston.png',
        teamColor: '#b94050',
        wins: 42,
        losses: 40,
    },
    {
        city: 'Indiana',
        nickname: 'Pacers',
        conference: 'East',
        card: 'teamcards/indiana.png',
        teamColor: '#121b3c',
        wins: 40,
        losses: 42,
    },
    {
        city: 'LAC',
        nickname: 'Clippers',
        conference: 'West',
        card: 'teamcards/lac.png',
        teamColor: '#ea3150',
        wins: 45,
        losses: 37,
    },
    {
        city: 'LAL',
        nickname: 'Lakers',
        conference: 'West',
        card: 'teamcards/lal.png',
        teamColor: '#70669b',
        wins: 43,
        losses: 39,
    },
    {
        city: 'Miami',
        nickname: 'Heat',
        conference: 'East',
        card: 'teamcards/miami.png',
        teamColor: '#e53736',
        wins: 38,
        losses: 44,
    },
    {
        city: 'Milwaukee',
        nickname: 'Bucks',
        conference: 'East',
        card: 'teamcards/milwaukee.png',
        teamColor: '#1e9744',
        wins: 31,
        losses: 51,
    },
    {
        city: 'Minnesota',
        nickname: 'Timberwolves',
        conference: 'West',
        card: 'teamcards/minnesota.png',
        teamColor: '#3462a0',
        wins: 15,
        losses: 67,
    },
    {
        city: 'New Jersey',
        nickname: 'Nets',
        conference: 'East',
        card: 'teamcards/new-jersey.png',
        teamColor: '#de275f',
        wins: 40,
        losses: 42,
    },
    {
        city: 'New York',
        nickname: 'Knicks',
        conference: 'East',
        card: 'teamcards/new-york.png',
        teamColor: '#ee7a27',
        wins: 51,
        losses: 31,
    },
    {
        city: 'Orlando',
        nickname: 'Magic',
        conference: 'East',
        card: 'teamcards/orlando.png',
        teamColor: '#306ea7',
        wins: 21,
        losses: 61,
    },
    {
        city: 'Philadelphia',
        nickname: '76ers',
        conference: 'East',
        card: 'teamcards/philadelphia.png',
        teamColor: '#e3333f',
        wins: 35,
        losses: 47,
    },
    {
        city: 'Phoenix',
        nickname: 'Suns',
        conference: 'West',
        card: 'teamcards/phoenix.png',
        teamColor: '#563a85',
        wins: 53,
        losses: 29,
    },
    {
        city: 'Portland',
        nickname: 'Trail Blazers',
        conference: 'West',
        card: 'teamcards/portland.png',
        teamColor: '#e93449',
        wins: 57,
        losses: 25,
    },
    {
        city: 'San Antonio',
        nickname: 'Spurs',
        conference: 'West',
        card: 'teamcards/san-antonio.png',
        teamColor: '#242021',
        wins: 47,
        losses: 35,
    },
    {
        city: 'Sacramento',
        nickname: 'Kings',
        conference: 'West',
        card: 'teamcards/sacramento.png',
        teamColor: '#3c65a2',
        wins: 29,
        losses: 53,
    },
    {
        city: 'Seattle',
        nickname: 'SuperSonics',
        conference: 'West',
        card: 'teamcards/seattle.png',
        teamColor: '#09a644',
        wins: 47,
        losses: 35,
    },
    {
        city: 'Utah',
        nickname: 'Jazz',
        conference: 'West',
        card: 'teamcards/utah.png',
        teamColor: '#423f4a',
        wins: 55,
        losses: 27,
    },
    {
        city: 'Washington',
        nickname: 'Bullets',
        conference: 'East',
        card: 'teamcards/washington.png',
        teamColor: '#e02a40',
        wins: 25,
        losses: 57,
    },
]